const alertPhrases = [
  'fuck off',
  'fuckoff',
  'fuckyou',
  'fuck you',
  'go fuck',
  'trey is a shill',
  'treys a shill',
  "trey's a shill",
  'fuck trey',
  'you asshole',
  'whats your problem',
  "what's your problem",
  'what is your problem',
  'whats ur problem',
  'your a shill',
  "you're a shill",
  'you are a shill',
  'your a idiot',
  'your an idiot',
  'youre an idiot',
  "you're an idiot",
  "you're a idiot",
  'your a bitch',
  "you're a bitch",
  'youre a bitch',
  'you cunt',
  'your a cunt',
  'you are a cunt',
  "you're a cunt",
  'dont be stupid',
  "don't be stupid",
  'you piece of shit',
  'you pos',
  "you're a piece of shit",
  "you're a pos",
  'your a piece of shit',
  'your a pos',
  'you douchebag',
  'your a douchebag',
  "you're a douchebag",
  'suck my dick',
  'eat a dick',
  'moms a whore',
  'moms a hoe',
  "mom's a whore",
  "mom's a hoe",
  'your a whore',
  'your a hoe',
  "you're a whore",
  "you're a hoe",
];

module.exports = alertPhrases;
